apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    # Домен, по которому доступна Grafana
    domain = grafana.pkdp.ru
    # URL, который Grafana будет использовать для редиректов
    root_url = %(protocol)s://%(domain)s/
    serve_from_sub_path = false
    http_port = 3000
    protocol = http

    [security]
    admin_user = admin
    admin_password = MSPrd123!

    [auth.anonymous]
    enabled = false

    [database]
    type = sqlite3
    path = /var/lib/grafana/grafana.db

    [log]
    mode = console
    level = info
